name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile
        cd backend && yarn install --frozen-lockfile
        cd ../operational_frontend && yarn install --frozen-lockfile

    - name: Build Applications
      run: |
        cd backend && yarn build
        cd ../operational_frontend && yarn build

    - name: Build and Push Docker Images
      if: github.ref == 'refs/heads/main'
      run: docker-compose build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.SSH_KEY }}" > deploy_key
        chmod 600 deploy_key
        ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /path-finder && docker-compose pull && docker-compose up -d"